language: r
r:
  - oldrel
  - release
cache: packages

r_packages:
- covr
- sodium

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libssl-dev
      - libgdal-dev
      - libproj-dev
      - gdal-bin

before_script:
- Rscript -e 'writeBin(sodium::data_decrypt(readRDS("rdhs.json.tar.enc"), sodium::hash(charToRaw(Sys.getenv("key")))),"rdhs.json.tar") ; unzip("rdhs.json.tar") ; Sys.setenv("rdhs_RENVIRON_PERMISSION"=1)'

after_success:
- Rscript -e 'covr::codecov()'

