language: r
cache: packages
r_packages:
- covr
addons:
  apt:
    packages:
    - libgdal-dev
    - libproj-dev
    - gdal-bin
after_success:
- Rscript -e 'covr::codecov()'
before_install:
- openssl aes-256-cbc -K $encrypted_23ddd56c4332_key -iv $encrypted_23ddd56c4332_iv
  -in credentials.tar.enc -out credentials.tar -d
