language: r

cache: packages

r_packages:
  - covr

addons:
  apt:
    packages:
      - gcc-4.9
      - g++-4.9

before_install:  |
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

env:
  global:
    - CODECOV_TOKEN="b290cc0e-4a34-4871-8884-1d5cb9382599"

after_success:
  - Rscript -e 'covr::codecov()'
