language: r
cache: packages

r_packages:
- covr
- sodium

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libssl-dev
      - libgdal-dev
      - libproj-dev
      - gdal-bin

after_success:
- Rscript -e 'covr::codecov()'

before_install:
- Rscript -e 'writeBin(sodium::data_decrypt(readRDS("credentials.tar.enc"), sodium::hash(charToRaw(Sys.getenv("key")))),"credentials.tar"") ; unzip("credentials.tar")'
